# Generated by Django 2.1.2 on 2018-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskType', models.CharField(max_length=100)),
                ('fieldName', models.CharField(max_length=100)),
                ('fieldData', models.CharField(max_length=1000)),
                ('fieldType', models.CharField(choices=[('False', 'False'), ('text', 'text'), ('number', 'number'), ('date', 'date')], default='False', max_length=100)),
                ('enumType', models.CharField(choices=[('False', 'False'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='False', max_length=100)),
            ],
        ),
    ]
